# Generated by Django 4.0 on 2021-12-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=125)),
                ('product_price', models.CharField(max_length=125)),
                ('product_image', models.ImageField(upload_to='products/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
