# Generated by Django 4.0 on 2021-12-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=125)),
                ('product_price', models.CharField(max_length=125)),
                ('product_image', models.ImageField(upload_to='products/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
