# Generated by Django 4.0 on 2021-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cart_product_total_alter_cart_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_total',
            field=models.IntegerField(default=0),
        ),
    ]
