# Generated by Django 4.0 on 2022-01-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_cart_product_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
